all:
  vars:
    sensorfleet_openvpn_server_connect_ip: 192.168.0.10
    ansible_user: root
  children:
    fleetmgmt:
      hosts:
        fleetmanagement:
          ansible_host: 192.168.0.10
          sensorfleet_openvpn_client_ip: 169.254.255.255
    sensors:
      hosts:
        sensor001:
          ansible_host: 192.168.1.101
          sensorfleet_openvpn_client_ip: 169.254.1.1
        sensor002:
          ansible_host: 192.168.2.102
          sensorfleet_openvpn_client_ip: 169.254.1.2
        sensor003:
          ansible_host: 192.168.3.103
          sensorfleet_openvpn_client_ip: 169.254.1.3
