---
- name: Install sshd_config
  ansible.builtin.template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: "0600"
    validate: "/usr/sbin/sshd -t -f %s"
  notify: Reload sshd

- name: Install SSH banner
  ansible.builtin.copy:
    dest: /etc/ssh/banner
    content: "{{ sensorfleet_ssh_server_banner }}\n"
    owner: root
    group: root
    mode: "0644"
  when: sensorfleet_ssh_server_banner is not none

- name: Ensure SSH banner is absent
  ansible.builtin.file:
    path: /etc/ssh/banner
    state: absent
  when: sensorfleet_ssh_server_banner is none

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
