[Service]
AmbientCapabilities=CAP_NET_ADMIN
CapabilityBoundingSet=CAP_IPC_LOCK CAP_NET_BIND_SERVICE CAP_NET_RAW CAP_SETGID CAP_SETUID CAP_SYS_CHROOT CAP_DAC_OVERRIDE CAP_AUDIT_WRITE
User=openvpn
Group=openvpn
RuntimeDirectory=openvpn-server
