[Service]
AmbientCapabilities=CAP_NET_ADMIN
CapabilityBoundingSet=CAP_IPC_LOCK CAP_NET_RAW CAP_SETGID CAP_SETUID CAP_SYS_CHROOT CAP_DAC_OVERRIDE
User=openvpn
Group=openvpn
RestartSec=10s
Restart=always
RuntimeDirectory=openvpn-client
