---
- name: Reload ferm ip rules
  ansible.builtin.command: ferm --domain ip /etc/ferm/ferm.conf
  listen: reload firewall rules
  changed_when: true
  failed_when: false

- name: Reload ferm ip6 rules
  ansible.builtin.command: ferm --domain ip6 /etc/ferm/ferm.conf
  listen: reload firewall rules
  changed_when: true
  failed_when: false

- name: Reload ferm eb rules
  ansible.builtin.command: ferm --domain eb /etc/ferm/ferm.conf
  listen: reload firewall rules
  changed_when: true
  failed_when: false
