---
- name: Set up SensorFleet hosts
  hosts: fleetmgmt:sensors
  roles:
    - role: sensorfleet_globals
      tags: [always]
    - role: sensorfleet_sanity_checks
      tags: [always]
    - role: sensorfleet_mounts
      tags: [mounts]
    - role: sensorfleet_internal_certificates
      tags: [internal_certificates]
    - role: sensorfleet_openvpn
      tags: [openvpn]
    - role: sensorfleet_system_cacerts
      tags: [system_cacerts]
    - role: sensorfleet_repos
      tags: [repos]
    - role: sensorfleet_services_ntp
      tags: [services_ntp]
    - role: sensorfleet_kernel
      tags: [kernel]
    - role: sensorfleet_sysctl
      tags: [sysctl]
    - role: sensorfleet_system
      tags: [system]
    - role: sensorfleet_logging
      tags: [logging]
    - role: sensorfleet_ssh
      tags: [ssh]
    - role: sensorfleet_nginx
      tags: [nginx]
    - role: sensorfleet_fleetgram
      tags: [fleetgram]
    - role: sensorfleet_firewall
      tags: [firewall]
    - role: sensorfleet_config
      tags: [config]
    - role: sensorfleet_usermgmt
      tags: [usermgmt]
    - role: sensorfleet_license
      tags: [license]
    - role: sensorfleet_instruments
      tags: [instruments]
